### ISSUE TITLE
 Bug: Shortened URL Contains Special Characters

### ISSUE THREAD

**Issue by gen-ai-py** [gen-ai-py/AICrafter#11]
The URL shortener generates shortened links that sometimes include special characters, which may cause issues when trying to access the shortened URL. The expected behavior is that the shortened link should only contain alphanumeric characters (A-Z, a-z, 0-9).

Steps to Reproduce:
Go to the URL shortener page.
Enter any valid URL (e.g., https://example.com).
Click on the "Shorten URL" button.
Check the generated shortened URL.
Occasionally, the shortened URL contains special characters like @, !, or %.
Expected Behavior:
The shortened URL should only contain alphanumeric characters (A-Z, a-z, 0-9) and no special characters.

Actual Behavior:
The shortened URL occasionally contains special characters, which can lead to invalid links.

Environment:
Browser: (e.g., Chrome, Firefox)
Operating System: (e.g., Windows 10, macOS 12)
Version: (e.g., 1.0.0)

Proposed Fix:
Ensure that the shortened URL generator function only uses alphanumeric characters by modifying the character set and updating the function.

Code with Bug:
function generateShortCode(length) {
  let result = '';
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@#$%!'; // Bug here, special characters are included
  for (let i = 0; i < length; i++) {
    const randomIndex = Math.floor(Math.random() * characters.length);
    result += characters[randomIndex];
  }
  return result;
}

Screenshot
![image](https://github.com/user-attachments/assets/2ef5f99d-0d0b-4ef7-8c41-ec1cc654d144)

**Comment by shbhmexe** [comment]
Can you assign this work to me? And I will always contribute to any issue, cause it makes me think and grow further

**Comment by gen-ai-py** [comment]
ok
